// This file is auto-generated by scripts/generate-story-order.mjs
// Do not edit manually - run: pnpm run generate-story-order
//
// Sources:
//   3DCarousel: src/views/3DCarousel/3DCarouselView.stories.tsx
//   Carousel: src/views/Carousel/CarouselView.stories.tsx
//   FacetCards: src/views/FacetCards/FacetCardsView.stories.tsx
//   HeatmapCalendar: src/views/HeatmapCalendar/HeatmapCalendarView.stories.tsx
//   InfiniteGallery: src/views/InfiniteGallery/InfiniteGalleryView.stories.tsx
//   LinearCalendar: src/views/LinearCalendar/LinearCalendarView.stories.tsx
//   ProjectFolders: src/views/ProjectFolders/ProjectFoldersView.stories.tsx

export const STORY_ORDERS = {
  "3DCarousel": [
    "Articles"
  ],
  "Carousel": [
    "FullExample",
    "Default",
    "HorizontalLayout",
    "VerticalLayout",
    "CircleShape",
    "RoundedShape",
    "WithTitleAndSubtitle",
    "ImageOnly",
    "HoverOverlay"
  ],
  "FacetCards": [
    "FullExample",
    "Default",
    "HorizontalLayout",
    "VerticalLayout",
    "CircleShape",
    "RoundedShape",
    "ImageOnly",
    "HoverOverlay"
  ],
  "HeatmapCalendar": [
    "FullExample",
    "Default",
    "CustomDuration",
    "ReverseColors",
    "VerticalLayout",
    "MonthGridView",
    "TypeTracking",
    "CustomColorSwatch"
  ],
  "InfiniteGallery": [
    "FullExample",
    "Default",
    "Masonry",
    "Polaroid"
  ],
  "LinearCalendar": [
    "FullExample",
    "Default",
    "AltVisualizations",
    "ColorsAndIcons"
  ],
  "ProjectFolders": [
    "FullExample",
    "Default",
    "ColorizedFiles"
  ]
} as const;
