
import { DEFAULT_CARD_SIZE, DEFAULT_CONTENT_MAX_LENGTH, DEFAULT_IMAGE_ASPECT_RATIO, DEFAULT_IMAGE_FIT, DEFAULT_LAYOUT, DEFAULT_OVERLAY_CONTENT_VISIBILITY, DEFAULT_REVERSE_CONTENT, DEFAULT_SHAPE, DEFAULT_SHOW_CONTENT, DEFAULT_SHOW_PROPERTY_TITLES, DEFAULT_SHOW_TITLE, DEFAULT_TILT } from "@/components/Card/config/constants";


import type { FacetCardsConfig } from "@/views/FacetCards/FacetCardsView";

export const DEFAULT_CONFIG: FacetCardsConfig = {
	layout: DEFAULT_LAYOUT,
	shape: DEFAULT_SHAPE,
	cardSize: DEFAULT_CARD_SIZE,
	imageProperty: "note.cover",
	imageAspectRatio: DEFAULT_IMAGE_ASPECT_RATIO,
	imageFit: DEFAULT_IMAGE_FIT,
	showTitle: DEFAULT_SHOW_TITLE,
	showPropertyTitles: DEFAULT_SHOW_PROPERTY_TITLES,
	showContent: DEFAULT_SHOW_CONTENT,
	contentMaxLength: DEFAULT_CONTENT_MAX_LENGTH,
	properties: [
    'note.author',
  ],
	reverseContent: DEFAULT_REVERSE_CONTENT,
	hoverProperty: undefined,
	hoverStyle: "none",
	overlayContentVisibility: DEFAULT_OVERLAY_CONTENT_VISIBILITY,
	badgeProperty: undefined,
	badgeIcon: undefined,
	badgeColor: undefined,
  tilt: DEFAULT_TILT,
  linkProperty: undefined,
} satisfies Partial<FacetCardsConfig>;

export const FULL_CONFIG: FacetCardsConfig = {
	...DEFAULT_CONFIG,
	layout: "horizontal",
	shape: "square",
	cardSize: 400,
	imageProperty: "note.banner",
	imageAspectRatio: 0.85,
	imageFit: "cover",
	showTitle: true,
	showPropertyTitles: false,
	properties: ["note.author", "note.published", "note.excerpt"],
	reverseContent: true,
	hoverProperty: "note.url",
	hoverStyle: "overlay",
  linkProperty: undefined,
} satisfies Partial<FacetCardsConfig>;

export const HORIZONTAL_LAYOUT_CONFIG: FacetCardsConfig = {
  ...DEFAULT_CONFIG,
  layout: 'horizontal',
  shape: 'square',
  hoverProperty: 'note.url',
  hoverStyle: 'overlay',
  properties: [
    'note.author',
    'note.published',
    'note.excerpt',
  ],
  imageProperty: 'note.banner',
  imageAspectRatio: 0.85,
  cardSize: 400,
  imageFit: 'cover',
  reverseContent: false,
  showPropertyTitles: false,
  showTitle: true,
  badgeProperty: undefined,
  badgeIcon: undefined,
  badgeColor: undefined,
  linkProperty: undefined,
}

export const OVERLAY_LAYOUT_CONFIG: FacetCardsConfig = {
  layout: 'overlay',
  shape: 'square',
  hoverProperty: undefined,
  hoverStyle: 'none',
  properties: [],
  imageProperty: 'note.cover',
  imageAspectRatio: 1.5,
  cardSize: 340,
  imageFit: 'cover',
  reverseContent: false,
  showPropertyTitles: false,
  showTitle: true,
  showContent: true,
  contentMaxLength: 200,
  overlayContentVisibility: 'always',
  badgeProperty: 'note.rating',
  badgeIcon: 'star',
  badgeColor: '#D0A215',
  tilt: DEFAULT_TILT,
  linkProperty: undefined,
}

export const CIRCLE_SHAPE_CONFIG: FacetCardsConfig = {
  layout: 'vertical',
  shape: 'circle',
  hoverProperty: undefined,
  hoverStyle: 'none',
  properties: [],
  imageProperty: 'note.cover',
  imageAspectRatio: 1,
  cardSize: 340,
  imageFit: 'cover',
  reverseContent: false,
  showPropertyTitles: false,
  showTitle: false,
  showContent: false,
  contentMaxLength: 200,
  overlayContentVisibility: 'always',
  badgeProperty: undefined,
  badgeIcon: undefined,
  badgeColor: undefined,
  tilt: DEFAULT_TILT,
  linkProperty: undefined,
}


export const ROUNDED_SHAPE_CONFIG: FacetCardsConfig = {
  layout: 'overlay',
  shape: 'rounded',
  hoverProperty: undefined,
  hoverStyle: 'none',
  properties: [],
  imageProperty: 'note.cover',
  imageAspectRatio: 1,
  cardSize: 340,
  imageFit: 'cover',
  reverseContent: false,
  showPropertyTitles: false,
  showTitle: true,
  showContent: false,
  contentMaxLength: 200,
  overlayContentVisibility: 'hover',
  badgeProperty: undefined,
  badgeIcon: undefined,
  badgeColor: undefined,
  tilt: DEFAULT_TILT,
  linkProperty: undefined,
}

export const POLAROID_LAYOUT_CONFIG: FacetCardsConfig = {
  ...DEFAULT_CONFIG,
  layout: 'polaroid',
  cardSize: 280,
  imageAspectRatio: 1,
  imageProperty: 'note.banner',
  showTitle: true,
  showPropertyTitles: false,
  properties: [],
  tilt: DEFAULT_TILT,
  linkProperty: undefined,
}
